services:
  harpia:
    container_name: harpia
    build:    
      context: .                                    #Dockerfile location
    privileged: True                                #Allows acess to host hardware 
    environment:
      - DISPLAY=:0                                  #Link the host display to container display
      - LANG=C.UTF-8 
      - LC_ALL=C.UTF-8 
      - ROS_DISTRO=jazzy
      - DEBIAN_FRONTEND=noninteractive 
      - NO_AT_BRIDGE=1 
      - PATH=$PATH:/root/.local/bin:/usr/local/bin
    volumes:  
      - ./harpia_ws/src:/root/harpia_ws/src:rwx     #Links host and container files
      - ~/.ssh:/root/.ssh:rwx                       #Enable ssh local keys to work inside of container to root
      - ~/.ssh:/home/harpia/.ssh:rwx                #Enable ssh local keys to work inside of container to harpia user
      - /etc/localtime:/etc/localtime:r             #Sets timezone 
      - /tmp/.X11-unix:/tmp/.X11-unix:rx            #Allows gui apps to run (Gazebo)
    network_mode: host                              #Share networks interface
    tty: True                                       #Keeps container running
